posts/urls.py
# coding=utf-8
from . import views
from django.urls import path

app_name = "posts"

urlpatterns = [
    path('', views.index, name="index"),
    path('post-list/', views.postList, name="post-list"),
    path('all-authors/', views.all_authors, name="all-authors"),
    path('results/', views.search, name="search"),
    path('new/', views.create, name="post-create"),
    path('<int:post_id>/', views.detail, name="post-detail"),
    path('edit/<int:post_id>/', views.edit, name="post-edit"),
    path('update/<int:post_id>/', views.update, name="post-update"),
    path('delete/<int:post_id>/', views.delete, name="post-delete"),
    path('post-list/templates/', views.byAuthor, name="post-authors")
]

reimnet_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/posts')),
    path('posts/', include('posts.urls', namespace="posts"))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    headline = models.CharField(max_length=500, null=False)
    content = models.TextField()
    publisher = models.ForeignKey(
        'auth.User', on_delete=models.DO_NOTHING, default=0)
    is_draft = models.BooleanField(default=True)
    date_published = models.DateTimeField()
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    picture = models.ImageField(
        upload_to='publisher_image', default="/upload3.jpeg")

    def __str__(self):
        """Return a human readable representation of the post model"""
        return self.title

    def get_absolute_url(self):
        """returns the URL to the detail view for the model"""
        return reverse('posts: post-detail', kwargs={'post_id': self.id})

posts/forms.py
# coding= utf-8
"""used to create forms for the posts module"""
from django.forms import forms
from .models import Post
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms


class PostForm(forms.Form):
    """Create and update form for Post DB model"""
    model = Postfields = ["title", "headline",
                          "content", "publisher", "is_draft"]

posts/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django import template
from django.http import HttpResponse
from .models import Post
from django.views import generic
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    """Display Home page"""
    return render(request, "posts/index.html", {})


def postList(request):
    """Post list view"""
    # reversing objects and turning into a list to access the length
    posts = Post.objects.all().filter(
        is_draft=False).order_by('-date_created')[0:10]
    context = {"posts": posts}
    return render(request, "posts/post_list.html", context)


def create(request):
    """Post create from view"""
    if request.method == "POST":
        form = PostForm(data=request.POSt)
        return redirect(to=post.get_absolute_url())

    # Render form if Get reguest
    return render(request, "posts/create.html", {})


def detail(request, post_id):
    """Post detail view"""
    post = get_object_or_404(Post, id=post_id)
    context = {"post": post}
    return render(request, "posts/detail.html", context)


def edit(request, post_id):
    """Post edit view"""
    message = "You are editing post of post id: %s" % str(post_id)
    return HttpResponse(message)


def update(request, post_id):
    """Post Update view"""
    message = "You are updating post of post id: %s" % str(post_id)
    return HttpResponse(message)


def delete(request, post_id):
    """Post Update view"""
    message = "You are deleting post of post id: %s" % str(post_id)
    return HttpResponse(message)


def byAuthor(request):
    """Display page by author"""
    posts = list(reversed(Post.objects.all()))
    names = Post.objects.all().filter(publisher__username="priye")
    context = {"posts": posts, "names": names}

    return render(request, "posts/byAuthor.html", context)


def search(request):
    """To carry out search functions"""
    template = "posts/results.html"
    query = request.GET.get('q')
    results = Post.objects.filter(
        Q(title__icontains=query) |
        Q(content__icontains=query) |
        Q(publisher__username__icontains=query)
    )
    return render(request, template, {"results": results})


def all_authors(request):
    """View all authors"""
    template = "posts/all_authors.html"
    posts = Post.objects.all()
    context = {"posts": posts}
    # final_list= []
    # for name in posts:
    #     if name not in final_list:
    #         final_list.append(name)

    # 'email', flat=True).distinct()

    return render(request, template, context)

posts/templates/posts/all_authors.html
{% extends "./base_generic.html" %}

{% block content %}

    <h1> All Posts Sorted By Author</h1>
    <hr>
    <div id="sidebar">
            <div class="row">
                    <div class="col-md-4">
                            <form id="searchform" action="{% url 'posts:search' %}" method="GET">
                                    {% comment %} {% csrf_token %} {% endcomment %}
                                    <input id="q" type="search" class="form-control" value="{{ request.GET.q }}" placeholder = "Search here" name="q" maxlength="100" style =" margin-bottom:5px;" required />
                                    <button class="btn btn-success" type="submit">Search</button>
                            </form>
                    </div>
                </div>
        <select onchange="location = this.value;">
            <option value="">Sort Posts</option>
            <option value ="{% url 'posts:post-authors' %}">By Author</option>
            <option value="{% url 'posts:post-list' %}">By Date</option></li>
        </select>
    </div>

    {% for post in posts %}
        <p id=myP>
            <li>{{ post.publisher }}</li>
        </p>

    {% endfor %}

{% endblock %}

posts/templates/posts/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
  <title>{% block title %}{% endblock %} | Reimnet</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block meta %}
    <meta name="Keywords" content="Reimnet,Blogs,posts,authors,learning,lessons,tips,websites">
    <meta name="Description" content="Reimnet blog is blogging platform for Reimnet employees used to make daily posts. ">
  {% endblock meta %}
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">

      {% block sidebar %}
      <ul class="sidebar-nav" style= "padding-top: 60px;" >
        <li><a href="{% url 'posts:index' %}">Home</a></li>
        <li><a href="{% url 'posts:post-list' %}">All Posts</a></li>
        <li><a href="{% url 'posts:all-authors' %}">All Authors</a></li>
      </ul>
     {% endblock %}

      </div>
      <div class="col-sm-10 ">

      {% block content %}
      
      {% endblock %}
      </div>
    </div>

  </div>

</html>

posts/templates/posts/byAuthor.html
{% extends "./base_generic.html" %}

{% block content %}

    <h1> All Posts Sorted By Author</h1>
    <hr>
    <div id="sidebar">
            <div class="row">
                    <div class="col-md-4">
                            <form id="searchform" action="{% url 'posts:search' %}" method="GET">
                                    {% comment %} {% csrf_token %} {% endcomment %}
                                    <input id="q" type="search" class="form-control" value="{{ request.GET.q }}" placeholder = "Search here" name="q" maxlength="100" style =" margin-bottom:5px;" required />
                                    <button class="btn btn-success" type="submit">Search</button>
                            </form>
                    </div>
                </div>
        <select onchange="location = this.value;">
            <option value="">Sort Posts</option>
            <option value ="{% url 'posts:post-authors' %}">By Author</option>
            <option value="{% url 'posts:post-list' %}">By Date</option></li>
        </select>
    </div>

    {% for post in  posts %}
        {% if post in names %}
            <div id="mydiv" style =" background-color:#0074D9;  color: hsla(208, 100%, 85%, 1.0); ">
                <img src= "{{ post.picture.url }} " alt="image">
                <h3>{{ post.title }}</h3>
                <h5>{{ post.headline }}</h5>
                <p><strong> Publisher: </strong> {{ post.publisher }}</p>
                <p><strong> Date Created:{{ post.date_created }} </strong></p>
                <a href = "{% url 'posts:post-detail' post.id %}" style = "color: white;">View Post </a><br/><br/>
            </div>

        {% else %}
            <div id="mydiv" style ="background-color:#39CCCC; float:right; margin-left: 20px;">
                <img src= "{{ post.picture.url }} " alt="image">
                <h3>{{ post.title }}</h3>                
                <h5>{{ post.headline }}</h5>
                <p><strong> Publisher: </strong> {{ post.publisher }}</p>
                <p><strong> Date Created: {{ post.date_created }} </strong></p>
                <a href = "{% url 'posts:post-detail' post.id %}"  style = "color: white;">View Post </a><br/><br/>
            </div>
        {% endif %} 
    {% endfor %}

{% endblock %}

posts/templates/posts/create.html
{% extends "./base_generic.html" %}
    <title>{{ post.title }}</title>
</head>
<body>
    <h1> Create New Post </h1>
    <hr>
    

    <form action = "" class ="form" method ="post">

        <button type = "submit" ></button>

    </form>

</body>
</html>

posts/templates/posts/detail.html
{% extends "./base_generic.html" %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

<h1>  Post by {{ post.publisher }}</h1>
<hr>

<body>
    <img src= "{{ post.picture.url }} " alt="image">
    <h1>{{ post.title }}</h1>
    <h3>{{ post.headline }}</h3>
    <h3>{{ post.content }}</h3>
            
</body>
</html>

{% endblock %}

posts/templates/posts/index.html
{% extends "./base_generic.html" %}

{% block content %}

<h1>Welcome to Reimnet Blog!</h1>
<hr/>

{% endblock %}

posts/templates/posts/name.html
{% extends "./base_generic.html" %}

{% block content %}


    {{ form }}
    

{% end block %}

posts/templates/posts/post_list.html
{% extends "./base_generic.html" %}

{% block title %}All Posts{% endblock title %}

{% block content %}

    
    <h1> All Posts</h1>
    <hr>
    {% comment %} {% url 'posts:get_name' %} {% endcomment %}
    
    <div class="row">
        <div class="col-md-4">
                <form id="searchform" action="{% url 'posts:search' %}" method="GET">
                        {% comment %} {% csrf_token %} {% endcomment %}
                        <input id="q" type="search" class="form-control" value="{{ request.GET.q }}" placeholder = "Search here" name="q" maxlength="100" style =" margin-bottom:5px;" required />
                        <button class="btn btn-success" type="submit">Search</button>
                </form>
        </div>
    </div>
    <select onchange="location = this.value;">
        <option value="">Sort Posts</option>
        <option value ="{% url 'posts:post-authors' %}">By Author</option>
        <option value="{% url 'posts:post-list' %}">By Date</option></li>
    </select>

    {% for post in posts %}
        {% if post.is_draft %}
            <div id="mydiv" style =" background-color:#0074D9;  color: hsla(208, 100%, 85%, 1.0); ">
                <img src= "{{ post.picture.url }} " alt="image">
                <p>Drafted message</p>
                <h3>{{ post.title }}</h3>
                <h5>{{ post.headline }}</h5>
                <p><strong> Publisher: </strong> {{ post.publisher }}</p>
                <p><strong> Date Created:{{ post.date_created }} </strong></p>
                <a href = "{% url 'posts:post-detail' post.id %}" style = "color: white;">View Post </a><br/><br/>
            </div>

        {% else %}
            <div id="mydiv" style ="background-color:#39CCCC; ">
                <img src= "{{ post.picture.url }} " alt="image">
                <p>Non-drafted message</p>
                <h3>{{ post.title }}</h3>                
                <h5>{{ post.headline }}</h5>
                <p><strong> Publisher: </strong> {{ post.publisher }}</p>
                <p><strong> Date Created: {{ post.date_created }} </strong></p>
                <a href = "{% url 'posts:post-detail' post.id %}"  style = "color: white;">View Post </a><br/><br/>
            </div>        
        {% endif %}

    

    {% endfor %}


{% endblock %}

posts/templates/posts/results.html
{% extends "./base_generic.html" %}

{% block content %}
    <h1> All Posts</h1>
    <p>{{ results|length }}</p>
    <hr>

    {% for result in results %}
        <div>
            <img src= "{{ result.picture.url }} " alt="image">
            <h3>{{ result.title }}</h3>
            <h5>{{ result.headline }}</h5>
            <p><strong> Publisher: </strong> {{ result.publisher }}</p>
            <p><strong> Date Created:{{ result.date_created }} </strong></p>
            <a href = "{% url 'posts:post-detail' result.id %}">View Post </a><br/><br/>
        </div>
    {% endfor %}
{% endblock %}